version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tfg_magic
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=24h
      - UPLOAD_PATH=uploads
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tfg_magic
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 